//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGestorEscolar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=david_Asus_Rog;Initial Catalog=Gestion_Escolar;Integrated Security=Tr" +
            "ue;TrustServerCertificate=True")]
        public string Gestion_EscolarConnectionString {
            get {
                return ((string)(this["Gestion_EscolarConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=david_asus_rog;Initial Catalog=Gestion_Escolar;Integrated Security=Tr" +
            "ue;TrustServerCertificate=True")]
        public string Gestion_EscolarConnectionString1 {
            get {
                return ((string)(this["Gestion_EscolarConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JOSUE;Initial Catalog=Gestion_Escolar;Integrated Security=True;Connec" +
            "t Timeout=30;Encrypt=True;TrustServerCertificate=True")]
        public string Gestion_EscolarConnectionString2 {
            get {
                return ((string)(this["Gestion_EscolarConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gestionescolar.database.windows.net;Initial Catalog=GestionEscolar;Us" +
            "er ID=admin_gestion_escolar;Password=Cisco!23Cisco!23;Connect Timeout=30;Encrypt" +
            "=True;TrustServerCertificate=False")]
        public string GestionEscolarConnectionString {
            get {
                return ((string)(this["GestionEscolarConnectionString"]));
            }
        }
    }
}
